# targets:
#   $default:
#     sources:
#       exclude:
#         - "**/*.dart"  # Exclude all Dart source files
#         - "bin/**"     # Exclude bin directory
#         - "lib/**"     # Exclude lib directory
#     builders:
#       build_web_compilers|entrypoint:
#         generate_for:
#           - web/main.dart
#         options:
#           dart2js_args:
#             - --minify