name: Deploy Dart Web App

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install webdev
        run: dart pub global activate webdev   
        
      - name: Add pub global to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH  

      - name: Build Dart Web App
        run: |
          dart pub get
          webdev build --output web:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          full_commit_message: Deploy web app to GitHub Pages
